fragment BlogParts on Blog {
  __typename
  title
  date
  excerpt
  featuredImage
  tags
  body
}

fragment ProductParts on Product {
  __typename
  title
  price
  category
  featuredImage
  shopifyLink
  body
}

fragment BranchParts on Branch {
  __typename
  title
  featuredImage
  body
}

fragment SiteConfigParts on SiteConfig {
  __typename
  mailchimp {
    __typename
    signupUrl
  }
  shopify {
    __typename
    storeUrl
  }
}
